# Generated by Django 5.1.4 on 2025-01-14 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_posts", "0002_article"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="is_checked",
            new_name="is_verified",
        ),
    ]
