# Generated by Django 5.1.4 on 2025-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_posts", "0003_rename_is_checked_comments_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
